import pytest

from pydantic import ValidationError

from aegis_ai.features.cve.data_models import (
    CriterionScore,
    CustomerLensAssessment,
    QualityRating,
    QualityReviewModel,
)

DISCLAIMER = (
    "This response was generated by Aegis AI "
    "(https://github.com/RedHatProductSecurity/aegis-ai) "
    "using generative AI for informational purposes. "
    "All findings should be validated by a human expert."
)

_CATEGORY_NAMES = [
    "Description — Technical Clarity",
    "Statement — Technical Clarity",
    "Mitigation",
    "Grammar & Style",
    "Content Ambiguity",
    "Technical Value — Customer Lens",
]

_CRITERION_IDS = [
    "criterion_0",
    "criterion_1",
    "criterion_2",
    "criterion_3",
    "criterion_4",
]


def _make_scores(category_scores: list[list[int]]) -> list[CriterionScore]:
    """Build a flat list of CriterionScore from 6 lists of criterion scores (one per category)."""
    scores = []
    for cat_name, cat_scores in zip(_CATEGORY_NAMES, category_scores):
        for crit_id, s in zip(_CRITERION_IDS, cat_scores):
            scores.append(
                CriterionScore(
                    category=cat_name,
                    criterion_id=crit_id,
                    score=s,
                    justification=f"Justification for {crit_id} in {cat_name}",
                )
            )
    return scores


def _make_review_model(category_scores: list[list[int]]) -> QualityReviewModel:
    """Build a full QualityReviewModel from 6 lists of criterion scores."""
    return QualityReviewModel(
        cve_id="CVE-2025-0001",
        scores=_make_scores(category_scores),
        customer_lens=CustomerLensAssessment(
            customer_can_decide=["Exposure scope"],
            remains_unclear=["Exploit likelihood"],
            manual_context_needed=["Deployment context"],
        ),
        strengths=["Clear description"],
        critical_gaps=["Missing statement"],
        recommendations=["Add a statement"],
        value_add="Provides Red Hat context not available in NVD",
        data_quality=0.8,
        confidence=0.7,
        tools_used=["osidb_tool"],
        disclaimer=DISCLAIMER,
    )


# --- QualityRating enum ---


def test_quality_rating_values():
    assert QualityRating.EXCELLENT.value == "Excellent"
    assert QualityRating.GOOD.value == "Good"
    assert QualityRating.NEEDS_IMPROVEMENT.value == "Needs Improvement"
    assert QualityRating.FAILS_STANDARDS.value == "Fails Standards"


# --- CriterionScore validation ---


def test_criterion_score_valid():
    cs = CriterionScore(
        category="Test", criterion_id="test", score=1, justification="ok"
    )
    assert cs.score == 1


def test_criterion_score_bounds_low():
    with pytest.raises(ValidationError):
        CriterionScore(
            category="Test", criterion_id="test", score=-1, justification="bad"
        )


def test_criterion_score_bounds_high():
    with pytest.raises(ValidationError):
        CriterionScore(
            category="Test", criterion_id="test", score=3, justification="bad"
        )


# --- QualityReviewModel score and rating ---


def test_quality_review_excellent():
    # 6 categories x [2,2,2,2,2] = 60 points
    model = _make_review_model([[2, 2, 2, 2, 2]] * 6)
    assert model.overall_score == 60
    assert model.rating == QualityRating.EXCELLENT


def test_quality_review_good():
    # 42 points: 6 categories x [2,1,1,1,2] = 7 each = 42
    model = _make_review_model([[2, 1, 1, 1, 2]] * 6)
    assert model.overall_score == 42
    assert model.rating == QualityRating.GOOD


def test_quality_review_needs_improvement():
    # 30 points: 6 categories x [1,1,1,1,1] = 5 each = 30
    model = _make_review_model([[1, 1, 1, 1, 1]] * 6)
    assert model.overall_score == 30
    assert model.rating == QualityRating.NEEDS_IMPROVEMENT


def test_quality_review_fails_standards():
    # 18 points: 6 categories x [1,1,1,0,0] = 3 each = 18
    model = _make_review_model([[1, 1, 1, 0, 0]] * 6)
    assert model.overall_score == 18
    assert model.rating == QualityRating.FAILS_STANDARDS


# --- printable_outcome ---


def test_printable_outcome():
    model = _make_review_model([[2, 2, 2, 2, 2]] * 6)
    assert model.printable_outcome() == "score=60/60 (Excellent)"


def test_printable_outcome_low_score():
    model = _make_review_model([[0, 0, 0, 0, 0]] * 6)
    assert model.printable_outcome() == "score=0/60 (Fails Standards)"


# --- Auto-computation ignores LLM-provided values ---


def test_overall_score_ignores_llm_provided_value():
    """overall_score and rating must be auto-computed, ignoring any values the LLM provides."""
    scores = _make_scores([[2, 2, 2, 2, 2]] * 6)

    # Pass wrong overall_score and rating — they should be overridden
    model = QualityReviewModel(
        cve_id="CVE-2025-0001",
        overall_score=5,  # wrong — should be auto-computed to 60
        rating=QualityRating.FAILS_STANDARDS,  # wrong — should be Excellent
        scores=scores,
        customer_lens=CustomerLensAssessment(
            customer_can_decide=["test"],
            remains_unclear=["test"],
            manual_context_needed=["test"],
        ),
        strengths=["test"],
        critical_gaps=["test"],
        recommendations=["test"],
        value_add="test",
        data_quality=0.8,
        confidence=0.7,
        tools_used=["osidb_tool"],
        disclaimer=DISCLAIMER,
    )
    assert model.overall_score == 60
    assert model.rating == QualityRating.EXCELLENT


# --- Rating boundary tests ---


def test_rating_boundary_48():
    """Score of exactly 48 should be Excellent."""
    # 48 = 6 categories x 8 each = [2,2,2,2,0] per category
    model = _make_review_model([[2, 2, 2, 2, 0]] * 6)
    assert model.overall_score == 48
    assert model.rating == QualityRating.EXCELLENT


def test_rating_boundary_47():
    """Score of 47 should be Good (just below Excellent threshold)."""
    # 47 = 5 categories x 8 + 1 category x 7
    cats = [[2, 2, 2, 2, 0]] * 5 + [[2, 2, 2, 1, 0]]
    model = _make_review_model(cats)
    assert model.overall_score == 47
    assert model.rating == QualityRating.GOOD


def test_rating_boundary_36():
    """Score of exactly 36 should be Good."""
    # 36 = 6 categories x 6 each = [2,2,2,0,0] per category
    model = _make_review_model([[2, 2, 2, 0, 0]] * 6)
    assert model.overall_score == 36
    assert model.rating == QualityRating.GOOD


def test_rating_boundary_24():
    """Score of exactly 24 should be Needs Improvement."""
    # 24 = 6 categories x 4 each = [2,2,0,0,0] per category
    model = _make_review_model([[2, 2, 0, 0, 0]] * 6)
    assert model.overall_score == 24
    assert model.rating == QualityRating.NEEDS_IMPROVEMENT


def test_rating_boundary_23():
    """Score of 23 should be Fails Standards."""
    # 23 = 5 categories x 4 + 1 category x 3
    cats = [[2, 2, 0, 0, 0]] * 5 + [[2, 1, 0, 0, 0]]
    model = _make_review_model(cats)
    assert model.overall_score == 23
    assert model.rating == QualityRating.FAILS_STANDARDS
